// apps/nuxt-catalog/app/components/RouteFrame.vue
<script setup lang="ts">
/**
 * RouteFrame — the shell every Nuxt variation renders inside.
 *
 * Provides the same contract as the React track's `RouteFrame`: a reserved 2.9rem chrome band (so a
 * variation's own header can never collide with the catalogue wordmark), a scroll-progress hairline,
 * the metadata HUD, and the `data-motion-ready` flag that unlocks the shared `will-change` hints.
 */
import type { Variation } from "@catalog/shared";

const props = defineProps<{ variation: Variation }>();

const { indexOf, total } = useCatalog();
const hub = useHubHref();
const progress = ref(0);
let frame = 0;

function measure() {
  const doc = document.documentElement;
  const max = doc.scrollHeight - window.innerHeight;
  progress.value = max > 0 ? Math.min(1, Math.max(0, window.scrollY / max)) : 0;
}

function onScroll() {
  cancelAnimationFrame(frame);
  frame = requestAnimationFrame(measure);
}

onMounted(() => {
  document.documentElement.dataset.motionReady = "true";
  measure();
  window.addEventListener("scroll", onScroll, { passive: true });
  window.addEventListener("resize", onScroll);
});

onUnmounted(() => {
  cancelAnimationFrame(frame);
  window.removeEventListener("scroll", onScroll);
  window.removeEventListener("resize", onScroll);
  delete document.documentElement.dataset.motionReady;
});
</script>

<template>
  <div class="cat-frame" :style="{ '--accent': variation.accent }">
    <div class="cat-progress" aria-hidden="true">
      <span class="cat-progress-bar" :style="{ transform: `scaleX(${progress})` }" />
    </div>

    <header class="cat-chrome">
      <a class="cat-mark cat-chrome-link" :href="hub">
        <span class="cat-mark-dot" aria-hidden="true" />
        THE CATALOG
      </a>
      <span class="cat-counter">
        {{ String(indexOf(variation.id)).padStart(2, "0") }} / {{ String(total).padStart(2, "0") }}
        <span class="cat-counter-sep" aria-hidden="true">·</span>
        {{ variation.discipline }}
      </span>
    </header>

    <main>
      <slot />
    </main>

    <CatalogHUD :variation="variation" :index="indexOf(variation.id)" :total="total" />
  </div>
</template>

// apps/next-catalog/src/components/RouteFrame.tsx
"use client";

/**
 * RouteFrame — the shell every variation renders inside.
 *
 * Provides: a scroll-progress hairline, the catalog wordmark with a live "n / total" counter
 * (useful when a client is clicking through the showroom), the metadata HUD, and the
 * `data-motion-ready` flag that unlocks the shared `will-change` hints.
 */
import { useEffect, useState } from "react";
import type { Variation } from "@catalog/shared";
import CatalogHUD from "./CatalogHUD";
import { hubHref, variations } from "@/lib/catalog";
import styles from "./RouteFrame.module.css";

export default function RouteFrame({ variation, children }: { variation: Variation; children: React.ReactNode }) {
  const [progress, setProgress] = useState(0);
  const [hub, setHub] = useState("/");

  useEffect(() => {
    document.documentElement.dataset.motionReady = "true";
    setHub(hubHref("/"));
  }, []);

  useEffect(() => {
    let raf = 0;
    const update = () => {
      const doc = document.documentElement;
      const max = doc.scrollHeight - window.innerHeight;
      setProgress(max > 0 ? Math.min(1, Math.max(0, window.scrollY / max)) : 0);
    };
    const onScroll = () => {
      cancelAnimationFrame(raf);
      raf = requestAnimationFrame(update);
    };
    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
  }, []);

  const index = variations.findIndex((v) => v.id === variation.id) + 1;

  return (
    <div className={styles.frame} style={{ ["--accent" as string]: variation.accent }}>
      <div className={styles.progressTrack} aria-hidden="true">
        <span className={styles.progressBar} style={{ transform: `scaleX(${progress})` }} />
      </div>

      <header className={styles.chrome}>
        <a className={styles.mark} href={hub}>
          <span className={styles.markDot} aria-hidden="true" />
          THE CATALOG
        </a>
        <span className={styles.counter}>
          {String(index).padStart(2, "0")} / {String(variations.length).padStart(2, "0")}
          <span className={styles.counterSep} aria-hidden="true">
            ·
          </span>
          {variation.discipline}
        </span>
      </header>

      <main className={styles.main}>{children}</main>

      <CatalogHUD variation={variation} />
    </div>
  );
}
